### PR TITLE
Add support for Django 2.1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zsoldosp** [comment]
thanks. don't forget to bump the version!

**Comment by zsoldosp** [comment]
@kairichard IMO the tox.ini is incorrect - bounds in merged pr are
2.0>,<2.2 which essentially drops 2.1 testing

**Comment by kairichard** [comment]
@zsoldosp correct - I missed that, thanks for pointing it out.

**Comment by kairichard** [comment]
Followup is this one https://github.com/PaesslerAG/django-admin-caching/pull/20

**Pull request merged**
